### ISSUE TITLE
Lock out user after 3 login attempts

### ISSUE THREAD

**Issue by ruzor** [microapidev/auth-microapi#441]
**Is your feature request related to a problem? Please describe.**

**Describe how to intend to go about adding this feature**
Describe the approach you will take in adding this feature.

**Additional context**

**Comment by mhizterkeyz** [comment]
Let me have this, please.

**Comment by mhizterkeyz** [comment]
Okay the problem is that people might try to break in by dictionary attacks or brute force. We can stop this by blocking out the user for sometime after 3 successive login failures.

I will solve this by adding a attempts object on the user model which holds the number of failed attempts and the time of last failed attempt. The app checks on there anytime user fails login and if the user has failed thrice, he gets blocked.

NO ADDITIONAL CONTEXT
